Repository TaloDev/godot, pull requests merged in 2025-02, with the labels that each got.

#65 Add API call for finding channels
  addons/talo/apis/channels_api.gd
Labels: enhancement

#66 Release 0.20.0
  addons/talo/apis/channels_api.gd
  addons/talo/plugin.cfg
Labels: release

#67 Add player presence API
  addons/talo/apis/channels_api.gd
  addons/talo/apis/game_config_api.gd
  addons/talo/apis/player_presence_api.gd
  addons/talo/entities/channel.gd
  addons/talo/entities/live_config.gd
  addons/talo/entities/player_presence.gd
  addons/talo/samples/chat/scripts/chat.gd
  addons/talo/talo_manager.gd
Labels: enhancement

#69 Add flag to control retrieving archived leaderboard entries
  addons/talo/apis/leaderboards_api.gd
  addons/talo/entities/leaderboard_entry.gd
  addons/talo/samples/leaderboards/scripts/leaderboard.gd
  addons/talo/samples/leaderboards/scripts/leaderboard_entry.gd
Labels: enhancement

#68 Release 0.21.0
  README.md
  addons/talo/apis/channels_api.gd
  addons/talo/apis/game_config_api.gd
  addons/talo/apis/leaderboards_api.gd
  addons/talo/apis/player_presence_api.gd
  addons/talo/entities/channel.gd
  addons/talo/entities/leaderboard_entry.gd
  addons/talo/entities/live_config.gd
  addons/talo/entities/player_presence.gd
  addons/talo/plugin.cfg
  addons/talo/samples/chat/scripts/chat.gd
  addons/talo/samples/leaderboards/scripts/leaderboard.gd
  addons/talo/samples/leaderboards/scripts/leaderboard_entry.gd
  addons/talo/talo_manager.gd
Labels: release

#82 Fix `PlayerAuthAPI.forgot_password()` has not handle error and change the type of `last_error` to `TaloAuthError`.
  addons/talo/apis/player_auth_api.gd
Labels: fix

#83 Let GameConfigAPI.get_live_config() return the TaloLiveConfig( useful for async program).
  addons/talo/apis/game_config_api.gd
Labels: enhancement

#84 Let some apis in PlayersAPI return `TaloPlayer` directly.
  addons/talo/apis/players_api.gd
  addons/talo/entities/player.gd
Labels: enhancement

#77 Add `EntriesPage`, `AddEntryResult` and use them instead of returning tuple like Array.
  addons/talo/apis/leaderboards_api.gd
  addons/talo/samples/leaderboards/scripts/leaderboard.gd
  addons/talo/samples/playground/scripts/add_entry_button.gd
  addons/talo/samples/playground/scripts/get_entries_button.gd
Labels: enhancement

#76 Add `ChannelPage` and use it instead of returning a tuple like Array.
  addons/talo/apis/channels_api.gd
  addons/talo/samples/chat/scripts/chat.gd
Labels: enhancement

#72 Add missing signals to ChannelsAPI: `player_joined`, `player_left`, `channel_ownership_transferred`, `channels_deleted`.
  addons/talo/apis/channels_api.gd
Labels: enhancement
